extra_css:
- styles/extra.css
nav:
- Inicio: index.md
- Contenidos: contenidos.md
- Bloque 1. Bioinformática:
  - Bioinformática (introducción): Bloque1_Bioinformatica/index.md
  - ADN y ARN: Bloque1_Bioinformatica/01_adn_arn.md
  - Secuenciación y Genoma: Bloque1_Bioinformatica/02_secuenciacion_genoma.md
  - Expresión génica y transcriptómica: Bloque1_Bioinformatica/03_expresion_genica_transcriptomica.md
  - Proteómica: Bloque1_Bioinformatica/04_proteomica.md
  - Bibliografía: Bloque1_Bioinformatica/bibliografia.md
- Bloque 2. Bases de datos genómicas:
  - Introducción: Bloque2_BD_Genomicas/index.md
  - Tipos y BD primarias/secundarias: Bloque2_BD_Genomicas/01_tipos_bd_primarias_secundarias.md
  - Alineamiento y comparación de secuencias: Bloque2_BD_Genomicas/02_alineamiento_comparacion.md
  - Análisis filogenéticos: Bloque2_BD_Genomicas/03_analisis_filogeneticos.md
  - Bibliografía: Bloque2_BD_Genomicas/bibliografia.md
- Bloque 3. Bioinformática estructural:
  - Introducción: Bloque3_Bioinformatica_Estructural/index.md
  - Estructuras 3D de macromoléculas: Bloque3_Bioinformatica_Estructural/01_estructuras_3d.md
  - Bases de datos estructurales: Bloque3_Bioinformatica_Estructural/02_bases_datos_estructurales.md
  - Predicción estructural: Bloque3_Bioinformatica_Estructural/03_prediccion_estructural.md
  - Bibliografía: Bloque3_Bioinformatica_Estructural/bibliografia.md
site_name: Bioinformática 40397
theme:
  name: material